### ISSUE TITLE
PSDtoSS6v2について

### ISSUE THREAD

**Issue by seikahara** [SpriteStudio/PSDtoSS6#19]
お世話になっております。
以前は同OSでv1.2.5を問題なく使用していましたが、v2.0.3を使おうとするとエラーが出て使用できませんでした。
OSはMacOS Mojave 10.14.4 なのですが、v2では対応外でしょうか？
教えていただければ幸いです。

エラー状況
1・PSDtoSS6 v2.0.3をDLをして初めて使用。ツールのスクリプトも更新。
2・各パーツと原点を指定するレイヤーが含まれた、キャンバスサイズ：2048×2048のPSDを用意
3 ・PSDデータをv2.0.3と同時に配布されたスクリプト「GeneratePivotLayer」を実行し、各パーツの中心点用レイヤーを作成・設定
4 ・「PSDtoSS_Export」を実行しコンバート、psdtoss-infoファイルが出来る。
5・PSDtoSS6でコンバート開始（ssae出力、sspj出力、原点レイヤー適用、rootレイヤー適用にチェック）
6・下記のエラーが出現します。

[-.txt](https://github.com/SpriteStudio/PSDtoSS6/files/3180648/-.txt)

**Comment by AkaneSera** [comment]
ウェブテクノロジ　瀬良です。
ご報告ありがとうございます。
本件調査いたしますので、少々お時間頂戴できれば幸いです。

解決まではVer.1.2.5をご利用いただければと思います。

ご迷惑をおかけしている中恐れ入りますが
よろしくお願いいたします。

**Comment by AkaneSera** [comment]
ウェブテクノロジ　瀬良です。

大変お待たせしており申し訳ございません。
ご報告いただいた問題に対処した「v2.0.3_fix1」を公開しました。
お手数おかけし重ね重ね恐れ入りますが、Updateをお願いいたします。

PSDtoSS6 v.2.0.3_fix1
https://github.com/SpriteStudio/PSDtoSS6/releases/tag/v2.0.3.fix

以上、何卒よろしくお願いいたします。

**Comment by seikahara** [comment]
お世話になっております。
調査していただきありがとうございます。
「v2.0.3_fix1」にUpdateしまして制作してみたら、問題なく使用できました。
迅速な対応ありがとうございました。
